[package]
name = "test-utils"
version = "0.3.9"
authors = ["encointer.org <alain@encointer.org>"]
edition = "2018"

[dependencies.encointer-ceremonies]
path = "../ceremonies"
package = "pallet-encointer-ceremonies"

[dependencies.encointer-communities]
path = "../communities"
package = "pallet-encointer-communities"

[dependencies.encointer-primitives]
package = "encointer-primitives"
path = "../primitives"

[dependencies.codec]
package = "parity-scale-codec"
features = ["derive"]
version = "2.0.0"

[dependencies.rstd]
package = "sp-std"
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-v1"

[dependencies.frame-system]
package = "frame-system"
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-v1"

[dependencies.frame-support]
package = "frame-support"
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-v1"

[dependencies.sp-core]
package = "sp-core"
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-v1"

[dependencies.sp-runtime]
package = "sp-runtime"
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-v1"

[dependencies.polkadot-parachain]
default-features = false
git = "https://github.com/paritytech/polkadot.git"
branch = "rococo-v1"

[dependencies.xcm]
git = "https://github.com/paritytech/polkadot.git"
branch = "rococo-v1"

[dependencies.xcm-builder]
git = "https://github.com/paritytech/polkadot.git"
branch = "rococo-v1"

[dependencies.xcm-executor]
git = "https://github.com/paritytech/polkadot.git"
branch = "rococo-v1"

[dependencies.balances]
package = "pallet-balances"
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-v1"

[dependencies.sp-keyring]
package = "sp-keyring"
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-v1"

[dependencies.sp-io]
package = "sp-io"
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-v1"

[dependencies.inherents]
package = "sp-inherents"
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-v1"

[dependencies.encointer-scheduler]
path = "../scheduler"
package = "pallet-encointer-scheduler"

[dependencies.encointer-balances]
path = "../balances"
package = "pallet-encointer-balances"

[dependencies.timestamp]
package = "pallet-timestamp"
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-v1"
